<?php

use Illuminate\Database\Seeder;
use App\GeoData\Seeders\AfghanistanSeeder;
use App\GeoData\Seeders\AlbaniaSeeder;
use App\GeoData\Seeders\AlgeriaSeeder;
use App\GeoData\Seeders\AndorraSeeder;
use App\GeoData\Seeders\AngolaSeeder;
use App\GeoData\Seeders\AntiguaandBarbudaSeeder;
use App\GeoData\Seeders\ArgentinaSeeder;
use App\GeoData\Seeders\ArubaSeeder;
use App\GeoData\Seeders\AustraliaSeeder;
use App\GeoData\Seeders\AustriaSeeder;
use App\GeoData\Seeders\BahamasSeeder;
use App\GeoData\Seeders\BarbadosSeeder;
use App\GeoData\Seeders\BelgiumSeeder;
use App\GeoData\Seeders\BelizeSeeder;
use App\GeoData\Seeders\BermudaSeeder;
use App\GeoData\Seeders\BoliviaSeeder;
use App\GeoData\Seeders\BrazilSeeder;
use App\GeoData\Seeders\CanadaSeeder;
use App\GeoData\Seeders\ChileSeeder;
use App\GeoData\Seeders\ChinaSeeder;
use App\GeoData\Seeders\ColombiaSeeder;
use App\GeoData\Seeders\CostaRicaSeeder;
use App\GeoData\Seeders\CroatiaSeeder;
use App\GeoData\Seeders\CubaSeeder;
use App\GeoData\Seeders\CzechRepublicSeeder;
use App\GeoData\Seeders\DenmarkSeeder;
use App\GeoData\Seeders\DominicanRepublicSeeder;
use App\GeoData\Seeders\EcuadorSeeder;
use App\GeoData\Seeders\ElSalvadorSeeder;
use App\GeoData\Seeders\EquatorialGuineaSeeder;
use App\GeoData\Seeders\FinlandSeeder;
use App\GeoData\Seeders\FranceSeeder;
use App\GeoData\Seeders\GermanySeeder;
use App\GeoData\Seeders\GreeceSeeder;
use App\GeoData\Seeders\GreenlandSeeder;
use App\GeoData\Seeders\GuatemalaSeeder;
use App\GeoData\Seeders\GuyanaSeeder;
use App\GeoData\Seeders\HaitiSeeder;
use App\GeoData\Seeders\HondurasSeeder;
use App\GeoData\Seeders\HongKongSeeder;
use App\GeoData\Seeders\IndiaSeeder;
use App\GeoData\Seeders\IndonesiaSeeder;
use App\GeoData\Seeders\IrelandSeeder;
use App\GeoData\Seeders\IsraelSeeder;
use App\GeoData\Seeders\ItalySeeder;
use App\GeoData\Seeders\IvoryCoastSeeder;
use App\GeoData\Seeders\JamaicaSeeder;
use App\GeoData\Seeders\JapanSeeder;
use App\GeoData\Seeders\LatviaSeeder;
use App\GeoData\Seeders\LebanonSeeder;
use App\GeoData\Seeders\LuxembourgSeeder;
use App\GeoData\Seeders\MalaysiaSeeder;
use App\GeoData\Seeders\MexicoSeeder;
use App\GeoData\Seeders\MoroccoSeeder;
use App\GeoData\Seeders\NetherlandsSeeder;
use App\GeoData\Seeders\NicaraguaSeeder;
use App\GeoData\Seeders\NigeriaSeeder;
use App\GeoData\Seeders\NorwaySeeder;
use App\GeoData\Seeders\PakistanSeeder;
use App\GeoData\Seeders\PanamaSeeder;
use App\GeoData\Seeders\PapuaNewGuineaSeeder;
use App\GeoData\Seeders\ParaguaySeeder;
use App\GeoData\Seeders\PeruSeeder;
use App\GeoData\Seeders\PhilippinesSeeder;
use App\GeoData\Seeders\PolandSeeder;
use App\GeoData\Seeders\PortugalSeeder;
use App\GeoData\Seeders\PuertoRicoSeeder;
use App\GeoData\Seeders\RomaniaSeeder;
use App\GeoData\Seeders\RussiaSeeder;
use App\GeoData\Seeders\SaintLuciaSeeder;
use App\GeoData\Seeders\SanMarinoSeeder;
use App\GeoData\Seeders\SingaporeSeeder;
use App\GeoData\Seeders\SouthAfricaSeeder;
use App\GeoData\Seeders\SpainSeeder;
use App\GeoData\Seeders\SriLankaSeeder;
use App\GeoData\Seeders\SwedenSeeder;
use App\GeoData\Seeders\SwitzerlandSeeder;
use App\GeoData\Seeders\ThailandSeeder;
use App\GeoData\Seeders\TurkeySeeder;
use App\GeoData\Seeders\UnitedKingdomSeeder;
use App\GeoData\Seeders\UnitedStatesSeeder;
use App\GeoData\Seeders\UruguaySeeder;
use App\GeoData\Seeders\VenezuelaSeeder;

class AllCountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ini_set('memory_limit', '512M');
    	DB::disableQueryLog();
        $this->call(AndorraSeeder::class);
        $this->call(SpainSeeder::class);
        $this->call(AfghanistanSeeder::class);
        $this->call(AlbaniaSeeder::class);
        $this->call(AlgeriaSeeder::class);
        $this->call(AngolaSeeder::class);
        $this->call(AntiguaandBarbudaSeeder::class);
        $this->call(ArgentinaSeeder::class);
        $this->call(ArubaSeeder::class);
        $this->call(AustraliaSeeder::class);
        $this->call(AustriaSeeder::class);
        $this->call(BahamasSeeder::class);
        $this->call(BarbadosSeeder::class);
        $this->call(BelgiumSeeder::class);
        $this->call(BelizeSeeder::class);
        $this->call(BermudaSeeder::class);
        $this->call(BoliviaSeeder::class);
        $this->call(BrazilSeeder::class);
        $this->call(CanadaSeeder::class);
        $this->call(ChileSeeder::class);
        $this->call(ChinaSeeder::class);
        $this->call(ColombiaSeeder::class);
        $this->call(CostaRicaSeeder::class);
        $this->call(CroatiaSeeder::class);
        $this->call(CubaSeeder::class);
        $this->call(CzechRepublicSeeder::class);
        $this->call(DenmarkSeeder::class);
        $this->call(DominicanRepublicSeeder::class);
        $this->call(EcuadorSeeder::class);
        $this->call(ElSalvadorSeeder::class);
        $this->call(EquatorialGuineaSeeder::class);
        $this->call(FinlandSeeder::class);
        $this->call(FranceSeeder::class);
        $this->call(GermanySeeder::class);
        $this->call(GreeceSeeder::class);
        $this->call(GreenlandSeeder::class);
        $this->call(GuatemalaSeeder::class);
        $this->call(GuyanaSeeder::class);
        $this->call(HaitiSeeder::class);
        $this->call(HondurasSeeder::class);
        $this->call(HongKongSeeder::class);
        $this->call(IndiaSeeder::class);
        $this->call(IndonesiaSeeder::class);
        $this->call(IrelandSeeder::class);
        $this->call(IsraelSeeder::class);
        $this->call(ItalySeeder::class);
        $this->call(IvoryCoastSeeder::class);
        $this->call(JamaicaSeeder::class);
        $this->call(JapanSeeder::class);
        $this->call(LatviaSeeder::class);
        $this->call(LebanonSeeder::class);
        $this->call(LuxembourgSeeder::class);
        $this->call(MalaysiaSeeder::class);
        $this->call(MexicoSeeder::class);
        $this->call(MoroccoSeeder::class);
        $this->call(NetherlandsSeeder::class);
        $this->call(NicaraguaSeeder::class);
        $this->call(NigeriaSeeder::class);
        $this->call(NorwaySeeder::class);
        $this->call(PakistanSeeder::class);
        $this->call(PanamaSeeder::class);
        $this->call(PapuaNewGuineaSeeder::class);
        $this->call(ParaguaySeeder::class);
        $this->call(PeruSeeder::class);
        $this->call(PhilippinesSeeder::class);
        $this->call(PolandSeeder::class);
        $this->call(PortugalSeeder::class);
        $this->call(PuertoRicoSeeder::class);
        $this->call(RomaniaSeeder::class);
       // $this->call(RussiaSeeder::class);
        $this->call(SaintLuciaSeeder::class);
        $this->call(SanMarinoSeeder::class);
        $this->call(SingaporeSeeder::class);
        $this->call(SouthAfricaSeeder::class);
        $this->call(SriLankaSeeder::class);
        $this->call(SwedenSeeder::class);
        $this->call(SwitzerlandSeeder::class);
        $this->call(ThailandSeeder::class);
        $this->call(TurkeySeeder::class);
        $this->call(UnitedKingdomSeeder::class);
        $this->call(UnitedStatesSeeder::class);
        $this->call(UruguaySeeder::class);
        $this->call(VenezuelaSeeder::class);
    }
}
